### PR TITLE
add warning before cascading deletion of customer

### LINKED ISSUE #134: Warn before cascading deletion of orders by customers if there are unfulfilled orders

### PR DESCRIPTION
**Pull request by creativequotient**
Fix #134 

This introduces a warning in the event that the customer that is being deleted has unfulfilled orders so as to prevent the unknowing deletion of unfulfilled order.

### CODE REVIEW

**Review by IanCKW — APPROVED** [review]
LGTM

**Comment by creativequotient** [comment]
Also changed all instances of `contacts` to `customer` in the UG.

**Review by Sharptail — APPROVED** [review]
LGTM

**Review by IanCKW — APPROVED** [review]
LGTM

**Pull request merged**
